### ISSUE TITLE
Meeting 2: Getting rolling in 2022

### ISSUE THREAD

**Issue by misterhtmlcss** [misterhtmlcss/df-mastermind#1]
Today let's keep it simple. Here is the proposed structure and we can all comment below a response to the structure or the content requested herein.

1. Post your update ex.
- What have you been working on?
- Goals between now and next meeting?
- Where are you stuck (optional)? **Suggestions: Can be technical? Can be about time management? Depression, etc. Think broadly what's inhibiting you.

2. If you are stuck and there is some need for greater detail; this happens. For example you may need help with something to do with CSS Grid and it's just making something align differently. You can see that's easy enough to describe, but what if it's something difficult like Mobx + Angular 1.x something it's hard to explain. Then just give a headline here, then open a new Issue on here and explain in detail. Screenshots, etc can all be included there.

What you want to think is that 6-7 people will comment after or before you and you want everyone to be able to scan easily what's been said and go out for more information. Also when you do create a new Issue to cover whatever you are stuck on then it is in a way your rubber ducky and it may in itself solve the problem. So really dig in as it's as much about you as it is about getting help too.

Just a reminder I'll post a README shortly to help with this process, but for now please always try to get your comment/issue in the morning of the day we are going to meeting at the latest. This isn't a hardline, but consider that if you want help then you may hope people actually thought about it before arriving versus not having time to consider it. So guideline, not rule. 

3. How is time broken down for tonights meeting: 
- 10min social to start
- 20min breakout. Self select, but we'll try keep it to 2 groups as discussed.
- 5min bio-break. Kids, bathroom, tequila
- 20min breakout. You can switch groups! OR not.
- 5min to wrap anything noteworthy; leave on your own time.
- 0min go straight to Github and hit the Readme setup for this week using a PR of course; there you add in writing your stated goals for next weeks meeting. **MUST do this as you leave the meeting unless you are racing off in an ambulance, your mother is calling, leg cramp, etc. Take serious as others may not circle back until the morning of our next meeting and it's important that we add to the readme and that everyone takes a moment to read what everyone else wrong. DON'T worry I will fight the merge conflicts for you. Just added your goals to your PR for the readme and read it before bed as I'll have it merged within the hour and well before you hit the sack.

Anything else? Remember despite all these decisions being made for you above I just did it for expedience and there is no emotional baggage from me if people want to make changes, etc. Also I'm not the leader, I'm the herder at this moment and as such I'd appreciate if others could collaborate with me outside of meetings in the way that Brian and Colin did by making all this happen in their own time.

**Comment by misterhtmlcss** [comment]
- What have I been working on?
I have been working on W1 for I.S. and also a contract for some HTML/CSS this week.

- Goal from last meeting achieved? Not achieved? Next meeting?
Don't recall having goals sadly, but it was to make progress on IS and survive another day with our newborn.
For next meeting I'd like to be done W2 and have read more of the POODR book. I love it, but it's harder to read when you are always exhausted by kids screaming and crying. 

- Where are you stuck?
Time management. I'm super stressed about time management. I'm so so worried about falling down due to physical exhaustion while my newborn challenges every night and my wife is under such a burden.  I have so much on my plate once I'm back at work that things will become even more challenging.

Need help with CSS Grid/CSS in general.

**Comment by MKCMMSK** [comment]
- What have I been working on?
  Working on implementing tests for work.

- Goal from last meeting achieved? Not achieved? Next meeting?
  No goals from last week as we were mostly setting up the structure for the mastermind groups,  for next meeting hopefully I'll have answers to my questions on testing and how to go about testing properly.

- Where are you stuck?
  Testing, testing, testing. I'm still having trouble gauging at what lengths we should be going with tests and structuring the tests at different levels. For example, my current approach to a project I'm working on is that I'm doing unit tests on the service level of the application (Most if not all logic goes here), integration tests will be done at the controller level (To be implemented). For the unit tests, I'd like to understand how you guys approach testing for inputs, number of calls being made, edge cases, mocking repositories, using stubs, fakes and mocks and so on and so forth.

**Comment by J-pilon** [comment]
- What have I been working on?
I've been working on the Imposter School blog project.

- Goal from last meeting achieved? Not achieved? Next meeting?
I didn't attend last weeks meeting but my recent goals are directed to organizing my days/weeks to be more productive but also to set aside time for recovery.

- Where are you stuck?
I'm stuck on a lot of things these days haha. Must mean that I'm pushing outside of what I'm comfortable with.
I would like to go over the git workflow of squash...rebase if we have time and also what are your guys thoughts on networking effectively.

**Comment by JakeFantin** [comment]
- What have I been working on?
I have been working on W2 of IS, as well a side job that involves doing customer service.

- Goal from last meeting achieved? Not achieved? Next meeting?
No meeting goal rn. Next meeting goal will be to attend at least 10 apartment showings and finish Week 3 of IS.

- Where are you stuck?
Getting off my ass. I think I have a long-term covid side effect that is making me crazy lethargic. I just want to sleep aaaalll the time. It's making work a real hassle.

**Comment by rhurtis** [comment]
What have I been working on?
- Fixing my CI/codecov and week 2 content.

Goal from last meeting achieved? Not achieved? Next meeting?
-N/A: Did not set a goal from the last meeting.

Where are you stuck?
-Carving out the time to work on the Blog and catching up.

**Comment by misterhtmlcss** [comment]
@rhurtis what is your goal for next meeting.
